# Generated by Django 2.1.4 on 2019-02-03 09:41

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='博客标题')),
                ('desc', models.TextField(verbose_name='博客摘要')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='博客内容')),
            ],
        ),
    ]
